FROM node:10-alpine as build

RUN mkdir /build
ADD package.json /build/package.json

WORKDIR /build/

RUN npm install


FROM node:10-alpine

EXPOSE 1337

COPY --from=build /build/node_modules /app/node_modules
COPY ./dist/ .

RUN npm install pm2@latest -g

WORKDIR /app/

CMD ["pm2" "start ./server.js"]
